apiVersion: v1
kind: Service
metadata:
  name: ums-backend
spec:
  selector:
    app: ums-backend
  ports:
    - port: 80
      targetPort: 8000
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ums-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ums-backend
  template:
    metadata:
      labels:
        app: ums-backend
    spec:
      containers:
        - name: ums-backend
          image: zaiats85/usm-express:version1.5
          ports:
            - containerPort: 8000
          env:
            - name: MONGO_URL
              value: mongodb://mongo:27017/ums
          imagePullPolicy: Always
