/********** CONNECTION **********/
export const SERVER_CONNECTED = 'SERVER_CONNECTED';
export const SERVER_DISCONNECTED = 'SERVER_DISCONNECTED';

/********** USERS **********/
export const GET_USERS_LIST_REQUEST = 'GET_USERS_LIST_REQUEST';
export const GET_USERS_LIST_SUCCESS = 'GET_USERS_LIST_SUCCESS';
export const GET_USERS_LIST_FAILURE = 'GET_USERS_LIST_FAILURE';

export const GET_USER_REQUEST = 'GET_USER_REQUEST';
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';
export const GET_USER_FAILURE = 'GET_USER_FAILURE';

export const GET_GROUPS_BY_USER_REQUEST = 'GET_GROUPS_BY_USER_REQUEST';
export const GET_GROUPS_BY_USER_SUCCESS = 'GET_GROUPS_BY_USER_SUCCESS';
export const GET_GROUPS_BY_USER_FAILURE = 'GET_GROUPS_BY_USER_FAILURE';

export const REMOVE_GROUP_FROM_USER_REQUEST = 'REMOVE_GROUP_FROM_USER_REQUEST';
export const REMOVE_GROUP_FROM_USER_SUCCESS = 'REMOVE_GROUP_FROM_USER_SUCCESS';
export const REMOVE_GROUP_FROM_USER_FAILURE = 'REMOVE_GROUP_FROM_USER_FAILURE';

export const ADD_GROUP_TO_USER_REQUEST = 'ADD_GROUP_TO_USER_REQUEST';
export const ADD_GROUP_TO_USER_SUCCESS = 'ADD_GROUP_TO_USER_SUCCESS';
export const ADD_GROUP_TO_USER_FAILURE = 'ADD_GROUP_TO_USER_FAILURE';


export const CREATE_USER_REQUEST = 'CREATE_USER_REQUEST';
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';
export const CREATE_USER_FAILURE = 'CREATE_USER_FAILURE';

export const UPDATE_USER_REQUEST = 'UPDATE_USER_REQUEST';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_FAILURE = 'UPDATE_USER_FAILURE';

export const DELETE_USER_REQUEST = 'DELETE_USER_REQUEST';
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';
export const DELETE_USER_FAILURE = 'DELETE_USER_FAILURE';

export const CLEAR_CURRENT_USER = 'CLEAR_CURRENT_USER';
export const CLEAR_USERS_ERROR = 'CLEAR_USERS_ERROR';
export const CLEAR_USERS_DATA = 'CLEAR_USERS_DATA';

export const SET_CURRENT_PAGE_USERS = 'SET_CURRENT_PAGE_USERS';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';

/********** GROUPS **********/
export const GET_GROUPS_LIST_REQUEST = 'GET_GROUPS_LIST_REQUEST';
export const GET_GROUPS_LIST_SUCCESS = 'GET_GROUPS_LIST_SUCCESS';
export const GET_GROUPS_LIST_FAILURE = 'GET_GROUPS_LIST_FAILURE';

export const GET_GROUP_REQUEST = 'GET_GROUP_REQUEST';
export const GET_GROUP_SUCCESS = 'GET_GROUP_SUCCESS';
export const GET_GROUP_FAILURE = 'GET_GROUP_FAILURE';

export const GET_USERS_BY_GROUP_REQUEST = 'GET_USERS_BY_GROUP_REQUEST';
export const GET_USERS_BY_GROUP_SUCCESS = 'GET_USERS_BY_GROUP_SUCCESS';
export const GET_USERS_BY_GROUP_FAILURE = 'GET_USERS_BY_GROUP_FAILURE';

export const CREATE_GROUP_REQUEST = 'CREATE_GROUP_REQUEST';
export const CREATE_GROUP_SUCCESS = 'CREATE_GROUP_SUCCESS';
export const CREATE_GROUP_FAILURE = 'CREATE_GROUP_FAILURE';

export const UPDATE_GROUP_REQUEST = 'UPDATE_GROUP_REQUEST';
export const UPDATE_GROUP_SUCCESS = 'UPDATE_GROUP_SUCCESS';
export const UPDATE_GROUP_FAILURE = 'UPDATE_GROUP_FAILURE';

export const DELETE_GROUP_REQUEST = 'DELETE_GROUP_REQUEST';
export const DELETE_GROUP_SUCCESS = 'DELETE_GROUP_SUCCESS';
export const DELETE_GROUP_FAILURE = 'DELETE_GROUP_FAILURE';

export const CLEAR_CURRENT_GROUP = 'CLEAR_CURRENT_GROUP';
export const CLEAR_GROUPS_ERROR = 'CLEAR_GROUPS_ERROR';
export const CLEAR_GROUPS_DATA = 'CLEAR_GROUPS_DATA';

export const SET_CURRENT_PAGE_GROUPS = 'SET_CURRENT_PAGE_GROUPS';
export const SET_CURRENT_GROUP = 'SET_CURRENT_GROUP';

/********** SESSION **********/
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';

export const CLEAR_SESSION_ERROR = 'CLEAR_SESSION_ERROR';

/********** MODAL **********/
export const SHOW_MODAL = 'SHOW_MODAL';
export const HIDE_MODAL = 'HIDE_MODAL';

export const MODAL_TYPE_CREATE_USER = 'MODAL_TYPE_CREATE_USER';
export const MODAL_TYPE_CREATE_GROUP = 'MODAL_TYPE_CREATE_GROUP';
export const MODAL_TYPE_ADD_GROUPS_TO_USER = 'MODAL_TYPE_ADD_GROUPS_TO_USER';
export const MODAL_TYPE_SUCCESS = 'MODAL_TYPE_SUCCESS';
export const MODAL_TYPE_ERROR = 'MODAL_TYPE_ERROR';

/********** SEARCH **********/
export const SEARCH_REQUEST = 'SEARCH_REQUEST';
export const SEARCH_SUCCESS = 'SEARCH_SUCCESS';
export const SEARCH_FAILURE = 'SEARCH_FAILURE';

export const CLEAR_SEARCH_RESULTS = 'CLEAR_SEARCH_RESULTS';

/********** SEARCH **********/
export const FETCH_REQUEST = 'FETCH_REQUEST';
export const FETCH_RECEIVE = 'FETCH_RECEIVE';
